name: shiki-backend

services:
  backend:
    build: .
    container_name: shiki-backend
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8082:8082"
    command: sh -c "php artisan storage:link || true && php artisan serve --host=0.0.0.0 --port=8082"

